FROM cccs/assemblyline-v4-service-base:latest

ENV SERVICE_PATH alsvc_resultsample.ResultSample

# Clone ExampleService service code
WORKDIR /opt/al/al_services/alsvc_resultsample
COPY alv4_service/alv4_service_example .