FROM sgaroncse/v4_service_base_dev:4.0.0

ENV SERVICE_PATH alsvc_exampleservice.ExampleService

# Clone ExampleService service code
WORKDIR /opt/al/al_services

COPY alv4_service/alv4_service_example /opt/al/al_services/alsvc_exampleservice