FROM cccs/assemblyline-v4-service-base-dev:latest

ENV SERVICE_PATH alsvc_exampleservice.ExampleService

# Clone ExampleService service code
WORKDIR /opt/al/al_services/alsvc_exampleservice
COPY alv4_service/alv4_service_example .